### ISSUE TITLE
[FEAT] (possibly) change system timestamp for logs

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/neon_debos#146]
### Objective

For troubleshooting purposes, log files are timestamped with 'America/Los_Angeles' {(PDT, -0700)} ; thereby causing users in other timezones to translate to local time- causing confusion with support issues/personnel.

### Initial Implementation Requirements

https://github.com/NeonGeckoCom/neon_debos/blob/dev/recipes/17-locale-config.yml may need to be modified for a local TZ
Use timedatectl for user input during a initial config OR use the Location &/or Time skills to configure.

### Other Considerations

Support personnel/writes ups would need to clarify times. - local vs. build time [America/Los_Angeles] vs. UTC
Persistent data storage of local TZ needs to be considered.
When the Location or Time skill makes changes - update with timedatectl {Location asks to update associated TZ}

**Comment by Olzeke51** [comment]
I can verify that an update [24.4.8, on Sat 20th], will revert back to TZ  'America/Los_Angeles'
To Clarify: even though Location or Time skills make changes - it is just for a local time-stamp -NOT the system time from the installed s/w -- afaict.

**Comment by NeonDaniel** [comment]
This should be doable by just keeping a user-specified `/etc/timezone` and `etc/localtime`

**Comment by Olzeke51** [comment]
it is going to take more than 'mana say-to "change my location to ...." and
respond 'yes' to the TZ change
/etc/timezone didn't change  -- maybe the user-specified data can be moved
to it ???

**Comment by NeonDaniel** [comment]
> it is going to take more than 'mana say-to "change my location to ...." and respond 'yes' to the TZ change

Yeah, I mostly wanted to just maintain any changes made with `timedatectl` to start. I'm not sure that I want to expose those system settings via skill intent since generally you wouldn't want to allow a user to make system-wide changes without authentication.

**Comment by Olzeke51** [comment]
speaking of authentication (since we are offline of Matirx, what is the
root password?
I notice neon is user 1005 , does that mean 1000 is available? ?
I tried to add myself to the 'adm' group [wanted to do more with the
journalctr options]
later, gator
gz

**Comment by NeonDaniel** [comment]
there is no root password set, but neon can `sudo su` to get access to the root account. UID 1000 should be available; `neon` is the only "regular" user defined

**Comment by NeonDaniel** [comment]
Reported as not fixed [on matrix](https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz:matrix.org/$ORJsWxD5fisOVAD7mT8bCV3rL_E8TrjXIB7FihbFz5Y?via=matrix.org&via=nitro.chat&via=rx.haunted.computer)

**Comment by Olzeke51** [comment]
@NeonDaniel  - if you are referring to my matrix chat, /etc/timezone is not readjusted - BUT local time and the timestamps in the various log files are updated.  I was focused on '/etc/timezone' and it appears it is not used much per Internet findings.
'/etc/localtime' is the primary source from most appearences and it holds between shutdown/reboot(s)
'
I would recommend closing this , unless other matrix users found a fault.  Gary
