### ISSUE TITLE
[BUG] Neon OS Release 24.07.24 - homescreen not fully populated

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/neon_debos#165]
### Description

fresh .img to usb/hdd , final boot process only shows wallpaper

### Steps to Reproduce

Mark II - sj201_R10, usb/hdd, no DSI - using HDMI
booted , waited , only wallpaper
loaded my configs via ssh/mana - was able to mouse the gui to 'reboot services'
second bootup did the same thing - only wallpaper

### Other Notes

was able to get a full homescreen by mousing the gui to the menu/homescreen
THEN I had a full information homescreen
sent 'troubleshooting package to "support" at jul-24_5-13 EDT

**Comment by NeonDaniel** [comment]
This usually happens because some service wasn't reporting ready yet.. I will look into the logs

**Comment by Olzeke51** [comment]
ALSO noted - the gui has the green border - like it is waiting for something !!

**Comment by NeonDaniel** [comment]
Appears to be missing the plugins needed for that config:
```
Could not find the plugin mycroft.plugin.stt.ovos-stt-plugin-serve
```

**Comment by Olzeke51** [comment]
I manually did a pip install of:  - - then the 'reboot services' 
ovos-ww-plugin-openwakeword
 ovos-stt-plugin-server

came back up with the green gui border - but no longer there after a 'hey neon, what time is it"
and I got a full homescreen
'
seems a little bit more than a UX

**Comment by NeonDaniel** [comment]
The border is dismissed when the listener is waiting for a WW again (after processing audio). If there's a failure, it isn't dismissed until the next valid interaction.

Definitely a bug in `ovos-shell`, though I don't know if we have anyone familiar enough with Qt to fix it.

**Comment by NeonDaniel** [comment]
Marked with "invalid" as that's the closest label to "belongs in other repository".

This is not new behavior and is attributable to a different project, so I'm closing this issue
