### ISSUE TITLE
[FEAT] make use of ramdisk for logging

### ISSUE THREAD

**Issue by denics** [NeonGeckoCom/neon_debos#26]
### Objective

At the moment, on the devkit, logs are saved in ``.local/config/neon``. I have noted that the image is also loading a ramdisk of 20Mb which is enough for storing logs. Why not make use of it?

### Initial Implementation Requirements

- you could simply create a symlink from ``.local/config/neon`` to ``/ramdisk``
- you could modify all init scripts to output logs to /ramdisk

### Other Considerations

If we do not use ramdisk for the logs, then it should be better remove it, in our little machines, 20Mb could be put at a better use than sit there

**Comment by NeonDaniel** [comment]
The logs should be saved at `~/.local/state/neon`, but in any case those should utilize the ramdisk. There might be some additional consideration for handling the log archives (currently handled as subdirectories in the log directory)
