### ISSUE TITLE
[BUG] It's easy to introduce (non-fatal) data restore errors in `check_update.sh` if new firstboot-type flags are created

### ISSUE THREAD

**Issue by strugee** [NeonGeckoCom/neon_debos#56]
### Description

See https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz:matrix.org/$xW4cEYllmP9OHDon0Sz4nBz2u8oQ_vCgrnGCEKRLU_g?via=matrix.org&via=nitro.chat&via=strugee.net for background discussion. tl;dr 0fc580eb9d1ff3f262bca5278c79b13a970ecae0 introduces a non-fatal `ENOENT` error during update because `do_bluetooth_config` has been introduced in the same update, so the first boot to create this file hasn't occurred yet. This is non-fatal currently but would become fatal if anyone ever added `set -e`, which isn't necessarily a bad idea.

### Other Notes

Suggested fix from Matrix:

> yeah, I was thinking there's not really any reason to not do those "if exists" checks for every file to be moved. could just refactor all those moves into a shell function

**Comment by NeonDaniel** [comment]
Good catch; I neglected to add those checks for the few signal files that are restored but it's valid for those not to exist so it makes sense to check if they do
